### ISSUE TITLE
Error when signtransaction in Sui wallet in version @suiet/wallet-kit@0.1.17

### ISSUE THREAD

**Issue by thienvip107** [suiet/wallet-kit#100]
Uncaught (in promise) Error: Transaction failed with the following error. Error executing transaction with request type: Error: RPC Error: The response returned from RPC server does not match the TypeScript definition. This is likely because the SDK version is not compatible with the RPC server. Please update your SDK version to the latest. Result received was: {"EffectsCert":{"certificate":{"transactionDigest":"FZ5ZdgXupt52DsR35SQzsfp9HDZu5U8xtGD3pavvh5mM","data":{"transactions":[{"Call":{"package":{"objectId":"0x9d4ec0c375dd96f27eb209fc4700072b9dbc6d64","version":1,"digest":"TLp6TWHzgmk8eFANJrK+d3fYiQaegJ09wqMKk/nq7Ck="},"module":"cf123","function":"init_inventory_and_listing"}}],"sender":"0xacd021b72dab0bfccad015b9e55dd8a8acb5d978","gasPayment":{"objectId":"0x09a29d48a9682ac361d4f5e1ee72828ec0c5d259","version":990,"digest":"NorStp5nsHPFE8PWWKIPoLDxXb9+aThLnREygo92Ag4="},"gasPrice":109,"gasBudget":10000},"txSignature":"AKd6MplFgJW/KZ98p896My8MaDnQ7rvoWgeLW92KhmH8A+oQ/u9lesSGZDAIV0ywkwU2rVA65edWMFGbycHTvgCrXQbO2LG8ily1zHN1CBRZopIYEV/tfP2U/21B+G8IgQ==","authSignInfo":{"epoch":5,"signature":"AZULiW41vwfeodnCe4GOLivC8yILX3OaCqOTMU0ZhuR2mVniPqcAldygikyuXGmIfA==","signers_map":[58,48,0,0,1,0,0,0,0,0,26,0,16,0,0,0,0,0,1,0,4,0,6,0,7,0,8,0,10,0,11,0,12,0,14,0,15,0,18,0,19,0,20,0,22,0,24,0,25,0,27,0,29,0,31,0,32,0,33,0,35,0,36,0,37,0,39,0,40,0]}},"effects":{"transactionEffectsDigest":"Nu/gLCN43wv4+jen2J3MzgT8g6JOxIbm18I69oJ67PM=","effects":{"status":{"status":"success"},"gasUsed":{"computationCost":32809,"storageCost":58,"storageRebate":16},"transactionDigest":"FZ5ZdgXupt52DsR35SQzsfp9HDZu5U8xtGD3pavvh5mM","created":[{"owner":{"Shared":{"initial_shared_version":991}},"reference":{"objectId":"0x0964fc427475a849a254c4b104d650112a22e4a7","version":991,"digest":"wz6kZY1zcDbPeQKkhMaln6UtjLuPXRfYxbGl42xcq1o="}},{"owner":{"AddressOwner":"0xacd021b72dab0bfccad015b9e55dd8a8acb5d978"},"reference":{"objectId":"0xdcc1a2cfff8fedd90627125210766eda8a8cda0e","version":991,"digest":"9nuMifbsi0ZvJgA8SVDvEqa91b8Vg9Ub2BR9H5seWLw="}}],"mutated":[{"owner":{"AddressOwner":"0xacd021b72dab0bfccad015b9e55dd8a8acb5d978"},"reference":{"objectId":"0x09a29d48a9682ac361d4f5e1ee72828ec0c5d259","version":991,"digest":"nh0qi+Y73k9SNKkg3mbqjsIKFxrPkF5AKPQ2TQ9nESU="}}],"gasObject":{"owner":{"AddressOwner":"0xacd021b72dab0bfccad015b9e55dd8a8acb5d978"},"reference":{"objectId":"0x09a29d48a9682ac361d4f5e1ee72828ec0c5d259","version":991,"digest":"nh0qi+Y73k9SNKkg3mbqjsIKFxrPkF5AKPQ2TQ9nESU="}},"events":[{"coinBalanceChange":{"packageId":"0x0000000000000000000000000000000000000002","transactionModule":"gas","sender":"0xacd021b72dab0bfccad015b9e55dd8a8acb5d978","changeType":"Gas","owner":{"AddressOwner":"0xacd021b72dab0bfccad015b9e55dd8a8acb5d978"},"coinType":"0x2::sui::SUI","coinObjectId":"0x09a29d48a9682ac361d4f5e1ee72828ec0c5d259","version":990,"amount":-32851}},{"newObject":{"packageId":"0x9d4ec0c375dd96f27eb209fc4700072b9dbc6d64","transactionModule":"cf123","sender":"0xacd021b72dab0bfccad015b9e55dd8a8acb5d978","recipient":{"Shared":{"initial_shared_version":991}},"objectType":"0x3a36e10ffd9a68382320aa06665eb4b3635812c6::listing::Listing","objectId":"0x0964fc427475a849a254c4b104d650112a22e4a7","version":991}},{"newObject":{"packageId":"0x9d4ec0c375dd96f27eb209fc4700072b9dbc6d64","transactionModule":"cf123","sender":"0xacd021b72dab0bfccad015b9e55dd8a8acb5d978","recipient":{"AddressOwner":"0xacd021b72dab0bfccad015b9e55dd8a8acb5d978"},"objectType":"0x3a36e10ffd9a68382320aa06665eb4b3635812c6::inventory::Inventory","objectId":"0xdcc1a2cfff8fedd90627125210766eda8a8cda0e","version":991}},{"moveEvent":{"packageId":"0x9d4ec0c375dd96f27eb209fc4700072b9dbc6d64","transactionModule":"cf123","sender":"0xacd021b72dab0bfccad015b9e55dd8a8acb5d978","type":"0x3a36e10ffd9a68382320aa06665eb4b3635812c6::listing::CreateListingEvent","fields":{"listing_id":"0x0964fc427475a849a254c4b104d650112a22e4a7"},"bcs":"CWT8QnR1qEmiVMSxBNZQESoi5Kc="}}],"dependencies":["82aghwoeykMk7FAg8XEZPGJFRPQyayxJhL86Zn2feqCZ","CjSTMRMcCn5z2dhmqFimwF2hxqwxZf11NKfKSouuYNSr"]},"authSignInfo":{"epoch":5,"signature":"AbjKTp0Ww12Xqj4zXQp1uRTHaZDWoj+Rj7PAzWxdlzLYWs06zcbvyv1Q167tRC4neA==","signers_map":[58,48,0,0,1,0,0,0,0,0,28,0,16,0,0,0,0,0,1,0,3,0,4,0,7,0,8,0,10,0,11,0,12,0,13,0,14,0,16,0,18,0,19,0,20,0,22,0,24,0,25,0,26,0,27,0,28,0,29,0,30,0,31,0,32,0,33,0,35,0,39,0,40,0]}},"confirmed_local_execution":true}}

**Comment by thienvip107** [comment]
i tried update lastest version of SUI wallet and wallet-kit but it's doesn't work

**Comment by fredliang44** [comment]
@thienvip107 hi, the Suiet Wallet Kit's SDK version already updated to the latest version `0.25.0` you can checkout here: https://github.com/suiet/wallet-kit/blob/3c68f788dcadccdc5448d97eb7d8045c9a407f65/packages/kit/package.json#L26

**Comment by fredliang44** [comment]
the reason might be currently devnet's sui fullnode version is not same as the testnet, so the data structure is differen across devnet & testnet

**Comment by fredliang44** [comment]
https://sui.io/resources-sui/testnet-wave-2-is-now-live/ You can checkout this documentation, testnet's Sui node version is locked at v0.22.0: 
![CleanShot 2023-01-31 at 01 42 37@2x](https://user-images.githubusercontent.com/22412638/215553159-ada14c02-8527-4756-a40b-2c16c50f3b50.png)

**Comment by fredliang44** [comment]
I just packed another wallet-kit version `0.1.17-testnet` with Sui sdk `v0.23.0`, this package should be capable with testnet, but not avaliable to devvnet.

**Comment by thienvip107** [comment]
ok , thanks
