### ISSUE TITLE
Error: [WalletError] Permission rejected

### ISSUE THREAD

**Issue by gavrushoves** [suiet/wallet-kit#113]
Can I detect using the useWallet hook when the user rejects the connection to the wallet.

![image](https://user-images.githubusercontent.com/30019200/220113774-7021a3b0-7e82-4cbf-a9cf-53ef34d57bc4.png)
![image](https://user-images.githubusercontent.com/30019200/220113910-2eb23bd3-5489-42de-8009-179b8c882bd7.png)

Maybe you have some method for this? I didn't find it in the documentation.

**Comment by bruceeewong** [comment]
Yeah that is an annoying compatible issue cuz wallets just throw different messages for this case. But for sure we'll handle this kind of dirty things, that's why we're here :) 
I am considering to throw an identical Error for developers to catch and handle (e.g. WalletError with code -100). Do you think that helps?

**Comment by gavrushoves** [comment]
Yes! This will be what I need. :)

**Comment by bruceeewong** [comment]
@gavrushoves Check out this pr #120 , we will lease it today

**Comment by bruceeewong** [comment]
@gavrushoves  We released it in v0.1.26. Feel free to upgrade your kit and change your codes by following the doc: https://kit.suiet.app/docs/components/ConnectButton#handle-connection-events

**Comment by gavrushoves** [comment]
@bruceeewong Can I handle this with my own button? For example wallet.onError or wallet.ErrorCode.

**Comment by bruceeewong** [comment]
@gavrushoves Yeah it's totally fine you can use try-catch block with async to achieve that:
```
// inside the handleClick function
try {
  await select(wallet.name);
} catch (err) {
  onConnectError(err as BaseError);
  return;
}
```

**Comment by gavrushoves** [comment]
Thanks! It works.
