### ISSUE TITLE
Autoconnect wallet

### ISSUE THREAD

**Issue by gavrushoves** [suiet/wallet-kit#121]
If we have autoconnect enabled <WalletProvider autoConnect={true}>. 
1. Use the wallet.disconnect() method and the wallet is disconnected. 
2. Reload the browser page and the wallet is connected again without an approval request.
3. If I reconnect to a wallet that was already connected before, then the authentication of the login to the wallet is also not requested.

**Comment by ChiuMungZitAlexander** [comment]
Facing the issue. After disconnect and refresh the page, it will be automatically connected.

**Comment by bruceeewong** [comment]
@gavrushoves @ChiuMungZitAlexander Hi there, the behavior you describe is expected. Would like to hear more about why does it bother you?

**Comment by ChiuMungZitAlexander** [comment]
It happens in some cases in our dApp that the user wants to disconnect wallet for some reasons (say, for switching address or for the security perhaps). We received the feedbacks from these users that after they disconnected and re-opened the page, the disconnected wallet address would be back there. Anyway, we would reply these feedbacks as you said this is expected.

Personally, I tried both `autoconnect` and `autoconnect={false}`.
- `autoconnect` - wallet will be auto connected after page reloads, even if the user disconnected the wallet.
- `autoconnect={false}` - everytime the page reloads, the user has to connected the wallet again.

It can be summarized like "always" or "ever". Maybe there would be a compromised option, which covers our situation.

Above is just my opinion, and appreciate your ideas.

**Comment by bruceeewong** [comment]
@ChiuMungZitAlexander Thanks for your detailed explaination. I would say if a user wanna stop connecting to a dapp, he/she should go to the wallet's settings and remove the dapp from the trusted approvals. (But I have to admit our Suiet wallet hasn't implemented that management yet. It should be supported soon.

**Comment by ChiuMungZitAlexander** [comment]
It is the exactly expected behavior that the user should remove trusted dapp from wallet. As these feedbacks are mostly from unexperienced users, we believe suiet is good enough for the majority. Thank you for the reply.
