### ISSUE TITLE
Does not work well with next.js 12 and 13 versions in production build

### ISSUE THREAD

**Issue by ansbr** [suiet/wallet-kit#123]
Hello! When I using next.js in develpoment ENV everything is ok, useWallet working well, I got right statuses.

Let's make that code:
```
  const wallet = useWallet();
  useEffect(() => {
    console.log(wallet?.status)
  }, [wallet?.status])
```

![image](https://user-images.githubusercontent.com/58120694/225375605-dccd3eb7-519b-48d4-9e28-e8c5438cb30b.png)

Everything is OK.

**BUT I caught the bug**, when I make next.js production build `yarn build` thent `yarn start`. Sometimes wallet status freeze in **connecting** status.
I thought maybe that some bugs on blockchain. But I try to investigate it, and I thought it bug in the your package.

### I understand how to reproduce that bug always:

- Take my new repository [https://github.com/ansbr/suiet-bugs](url).  It is fresh next.js app with one commit [https://github.com/ansbr/suiet-bugs/commit/125785b8af458c2e06df7458ce6250ee832f4568](url)
- Clone it, `yarn install` -> `yarn build` -> `yarn start` or use _npm_
- Open [http://localhost:3000](url)
- Connect to wallet with your component
- Then open developer console, go to Network tab, and choose Fast 3G
![image](https://user-images.githubusercontent.com/58120694/225378885-cba98b93-2182-48e0-8a44-a417f3ae32c9.png)
- Refresh page without reset cache.
- You got result, button is blue, status **connecting** is freezed
![image](https://user-images.githubusercontent.com/58120694/225379392-71cc405f-b731-4ba6-9f99-d7ff0dc054fd.png)
- If you will try connect one more time, you got error in console
![image](https://user-images.githubusercontent.com/58120694/225379550-42c1115f-1d22-4839-9414-1a6ab16f7b74.png)

That bug is very annoying for me, I and my team saw it every day (without throttling). Can you fix it?

**Thank you**.

**Comment by bruceeewong** [comment]
@ansbr Hi, can you help us to confirm if the issue still exist?

**Comment by ansbr** [comment]
@bruceeewong Hi, I update packages.json
```
    "@mysten/sui.js": "^0.30.0",
    "@suiet/wallet-kit": "0.2.3",
```

But modal did not see suiet extension
![image](https://user-images.githubusercontent.com/58120694/228651194-2aa465d5-8255-4aa4-8bd2-410322133835.png)


I update suiet extension too, but problem is not gone. Now I have extension version 0.2.0

**Comment by bruceeewong** [comment]
@ansbr Yeah the wallet kit has upgraded to new wallet standard, but our wallet's new version 0.2.1 is still reviewing. In these two days this issue would be gone naturally. 

You can play with Sui Wallet for now.

**Comment by ansbr** [comment]
@bruceeewong As I remember for Sui Wallet everything was ok. That Bug appears only for Suiet Wallet, so I need to wait new version of Suiet Wallet for check it.

Anyway, now Sui Wallet working well too.

**Comment by ansbr** [comment]
@bruceeewong Unfortunately, this bug still remains unresolved. I have `"@suiet/wallet-kit": "^0.2.4"`, and I'm using Suiet Wallet version 0.2.3 in Chrome.

**Comment by bruceeewong** [comment]
@ansbr things should work now, help us check it again?
