### ISSUE TITLE
can‘t open sui wallet

### ISSUE THREAD

**Issue by monicacheng123** [suiet/wallet-kit#132]
Hello, I have a problem now.
when i use : https://wallet-kit-demo.vercel.app/
I can't open sui wallet  like this:

<img width="318" alt="image" src="https://user-images.githubusercontent.com/122587212/228465994-499c97c5-6400-4d76-992f-0ed1732c76ee.png">

However i have Sui wallet,but the problem still exists.

<img width="971" alt="image" src="https://user-images.githubusercontent.com/122587212/228468365-bfca262c-e8a1-4e02-b954-b353ab696b09.png">

**Comment by bruceeewong** [comment]
Hey guys @ser25 @monicacheng123 , we've updated this demo, and now it should work well with Sui wallet
