### ISSUE TITLE
Cannot convert a BigInt

### ISSUE THREAD

**Issue by gavrushoves** [suiet/wallet-kit#135]
After switching from "@suiet/wallet-kit": "^0.1.26" to "@suiet/wallet-kit": "^0.2.4" I didn't have any problems locally. But after deploying the react js application to the server, the application broke with such an error.

![image](https://user-images.githubusercontent.com/30019200/229097626-bc4d8a3f-7f77-4b06-ad09-dc32df708272.png)

![image](https://user-images.githubusercontent.com/30019200/229097820-285b1668-afc4-4fd5-9955-89300d97860d.png)

**Comment by gavrushoves** [comment]
Even if I remove all imports of methods and WalletProvider. And just leave the installed package @suiet/wallet-kit. I get this error after deploying my dapp.

**Comment by bruceeewong** [comment]
@gavrushoves I confirm that it's because of the mysten ts sdk which requires bigint compatible bundling. Just search for the appropriate bundling configs for your dapp

**Comment by gavrushoves** [comment]
> @gavrushoves I confirm that it's because of the mysten ts sdk which requires bigint compatible bundling. Just search for the appropriate bundling configs for your dapp

Sorry, but I didn't understand what I need to look for.

**Comment by gavrushoves** [comment]
I added this code to my package.json and it helped. Thanks for the help.
`"browserslist": {
    "production": [
      "chrome >= 67",
      "edge >= 79",
      "firefox >= 68",
      "opera >= 54",
      "safari >= 14"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }`
