### ISSUE TITLE
Error when signing message

### ISSUE THREAD

**Issue by jrlimtiaco** [suiet/wallet-kit#144]
Im running the `next` example provided in the repo and get an error when signing a message `bad signature size`. It appears the error happens here https://github.com/suiet/wallet-kit/blob/main/examples/with-next/components/App.tsx#L66-L70

I also get the same error when signing a message on the deployed app https://wallet-kit-demo.vercel.app

<img width="432" alt="Screen Shot 2023-04-14 at 5 38 03 PM" src="https://user-images.githubusercontent.com/25376058/232174493-b3d8ad82-ae9b-4a72-8bd3-cf5e11b48910.png">

**Comment by bruceeewong** [comment]
Problem solved. Please try with @suiet/wallet-kit with v0.2.7 version. 
Details for pr: https://github.com/suiet/wallet-kit/pull/147

**Comment by anhskohbo** [comment]
Issues still there, even try with `wallet.verifySignedMessage(signed);`

```
      const signed = await walletAdapter.signMessage({
        message: (new TextEncoder()).encode('a'),
      });

      console.log(signed);

      const xx = walletAdapter.verifySignedMessage(signed);
```

**Comment by bruceeewong** [comment]
@anhskohbo Hi, if you are trying with Suiet wallet, please update your wallet to version v0.2.7.
And for Sui wallet, it should work.
