### ISSUE TITLE
useWallet does not identify installed wallets correctly

### ISSUE THREAD

**Issue by ktomascz** [suiet/wallet-kit#146]
`configuredWallets ` attribute does not identify installed wallets correctly. 

While having 'GlassWallet' extension installed the hook still returns installed as **false**. 
`{name: 'GlassWallet', iconUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAA…fDrA16c3sXFqPP9KFPa78f3JWYVNfaX2rAAAAAElFTkSuQmCC', downloadUrl: {…}, adapter: undefined, installed: false}`

installed should be **true** in this case. 

This has been reported for following wallets: GlassWallet, OneKey Wallet, Spacecy Sui Wallet a Surf Wallet
So far, I have tested with just the GlassWallet

**Comment by bruceeewong** [comment]
Please update your kit to v0.2.x version. 
Details for this issue: https://kit.suiet.app/docs/migration/upgradeTo0.2.x#major-breaking-change---new-wallet-standard

**Comment by ktomascz** [comment]
I am sorry, in the rush I forgot to mention the obvious. 

"@suiet/wallet-kit": "^0.2.4"
"@mysten/sui.js": "0.30.0"  

I have tried to bump both up to the latest versions and the issue remained. 
Maybe I have missed something? 
Does these wallet work for you ok (if installed)?

**Comment by bruceeewong** [comment]
Please update Sui sdk to the latest (0.32.1 by now): https://www.npmjs.com/package/@mysten/sui.js

**Comment by ktomascz** [comment]
Everything updated. 
All seems to be working fine. 
Closing this issue.

Thank you.
