### ISSUE TITLE
Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)

### ISSUE THREAD

**Issue by YYsuni** [suiet/wallet-kit#150]
After installing @suiet/wallet-kit, my project is no longer able to start.
![image](https://user-images.githubusercontent.com/53907086/233950268-92ab00e4-13aa-4dc6-ac33-d78524babc80.png)

**Comment by bruceeewong** [comment]
Duplicate solved issues: #135 
Please check the previous solution~

**Comment by YYsuni** [comment]
Adding browserslist is not useful for me, but I found a solution in https://github.com/sveltejs/kit/issues/859

**Comment by bruceeewong** [comment]
Yeah the solution should be related to what building tool u are using. Good for you.

**Comment by YYsuni** [comment]
Yes, thanks!
