### ISSUE TITLE
I have enough money, but it says I don't have enough gas

### ISSUE THREAD

**Issue by songenen** [suiet/wallet-kit#153]
<img width="956" alt="image" src="https://user-images.githubusercontent.com/59854272/234868797-d767b059-aec1-414a-8c97-3903a00ca35d.png">

## My money is all in one place, how can I split it up and use it for gas?

<img width="610" alt="image" src="https://user-images.githubusercontent.com/59854272/234872525-09e5da29-62e6-47c7-b37c-2a21b1b4cb48.png">

![image](https://user-images.githubusercontent.com/59854272/234872782-206505bd-8018-40ed-9d9a-7f9eb1c62630.png)

**Comment by bruceeewong** [comment]
Hey, would you please confirm your wallet version?

**Comment by songenen** [comment]
I found the problem, it was me repeating pure twice
now It's ok
```javascript
const [coin] = tx.splitCoins(tx.gas, [tx.pure(price)]);
const arr = [
    marketID,
    CollectionId,
    data.data.objectId,
    coin,
    address,
]
tx.moveCall({
    target: `${packageObjectId}::market::buy_and_take_script`,
    typeArguments: [typeArg],
    arguments: arr.map((item: any,i:number) =>i===3?item: tx.pure(item))
})
tx.transferObjects([coin], tx.pure(address))
```
