### ISSUE TITLE
Request for documentation

### ISSUE THREAD

**Issue by georgescharlesbrain** [suiet/wallet-kit#188]
I'd like to learn more why I should start with "suiet wallet-kit" and not other options.
Mainly I want to understand what the relation/comparison is between "suiet wallet-kit" and

[sui wallet-standard](https://github.com/MystenLabs/sui/tree/main/sdk/wallet-adapter/wallet-standard)
[sui wallet-kit](https://github.com/MystenLabs/sui/tree/main/sdk/wallet-adapter/wallet-kit)
[ethos connect](https://docs.ethoswallet.xyz/)

**Comment by bruceeewong** [comment]
Hi, @georgescharlesbrain . Basically, these are three kits that all implement the [Sui wallet standard](https://github.com/MystenLabs/sui/tree/main/sdk/wallet-adapter/wallet-standard), so you are good to try with either of them. The key difference among them I would say is the style of out-of-the-box UI components and the API design. So you can choose them based on your programming preferences and product design needs.

**Comment by georgescharlesbrain** [comment]
Thanks will look into it further then.
