### ISSUE TITLE
Dry run failed, could not automatically determine a budget

### ISSUE THREAD

**Issue by ser25** [suiet/wallet-kit#193]
I have this problem, how can I solve it 
Dry run failed, could not automatically determine a budget: MoveAbort(MoveLocation { module: ModuleId { address: 773b0bc40977f923354c53c85957e3f2f55149d1a4d2797d0bb5758db48a50c3, name: Identifier("nft_stake") }, function: 9, instruction: 20, function_name: Some("stake") }, 2) in command 1 (code: -1)

**Comment by bruceeewong** [comment]
"could not automatically determine a budget" from my experience, this error usually is related to insufficient balance. Can you double check your SUI balance?
