### ISSUE TITLE
JS this context error

### ISSUE THREAD

**Issue by Lagoonp** [suiet/wallet-kit#201]
When I use the following writeup it is called successfully.

```typescript
  const provider = useSuiProvider(SuiConfig.rpc)
  provider.getBalance({ owner: address, coinType: '0x2::sui::SUI' })  
```

But when I unfolded it, The "**client**" does not exist.

```typescript
 const { getBalance } = useSuiProvider(SuiConfig.rpc)
 getBalance({ owner: address, coinType: '0x2::sui::SUI' })  
```

**Comment by bruceeewong** [comment]
Yeah I think the problem is the returned object from useSuiProvider is an instance of "JsonRpcProvider", which is a stateful class instead of plain js object. So I would suggest keeping the reference as it is.

**Comment by bruceeewong** [comment]
Close this issue for not receiving responses.
