### ISSUE TITLE
npm install '@suiet-wallet' not found

### ISSUE THREAD

**Issue by JOEYLEE1121** [suiet/wallet-kit#202]
Hello I am trying to use useAccountBalance hook, but seems like I cannot get the correct library.
I can access useWallet hook from '@suiet/wallet-kit' but not useAccountBalance.
Is the '@suiet/wallet' currently not published or is there other way to use the hook?
I am following the instructions from the Suiet Wallet Kit documentation.
Thank you.

**Comment by bruceeewong** [comment]
Hi, would you mind confirming your version of wallet kit? I've tried with v0.2.16 and useAccountBalance is accessible from '@suiet/wallet-kit'. If there is still confusion I would suggest checking this example: https://github.com/suiet/wallet-kit/blob/main/examples/with-vite/src/App.tsx#L24

**Comment by bruceeewong** [comment]
Close this issue for not receiving active responses
