### ISSUE TITLE
Wallet verify signed message failed

### ISSUE THREAD

**Issue by vunguyen9404** [suiet/wallet-kit#203]
Hi, 
I have tried to sign a message and verify a signed message. The sign message works fine, but the verify function returns an error. 
I am using wallet-kit v0.2.16. 
Currently, the same error appears on the wallet-kit-demo as well.
https://wallet-kit-demo.vercel.app/

Image:
![image](https://github.com/suiet/wallet-kit/assets/22277763/8ab3edfd-a9ae-4fd9-883c-4220e1614e65)

**Comment by norbubb** [comment]
same error

**Comment by bruceeewong** [comment]
@vunguyen9404 @norbubb @luoxiaojiang Hi all, try the new version of kit v0.2.17. This issue should be fixed. Note that there is a change in the input params of verifySignedMessage. You can take the updated example as reference to modify your existing code:
https://github.com/suiet/wallet-kit/blob/main/examples/with-vite/src/App.tsx#L68
