### ISSUE TITLE
SignMessage succeed, but verify signedMessage failed when I use 'Sui Wallet' and 'Suiet' to sign. But it was all right before update.

### ISSUE THREAD

**Issue by Leeejuan** [suiet/wallet-kit#225]
SignMessage succeed, but verify signedMessage failed when I use 'Sui Wallet' and 'Suiet' to sign. But it was all right before update.

**Comment by bruceeewong** [comment]
Duplicated #203 
Please follow the instructions there. Feel free to give feedback if there is still any error.
