### ISSUE TITLE
devnet can not execute transaction today

### ISSUE THREAD

**Issue by qxyanda** [suiet/wallet-kit#242]
my code does not change, it worked well last night, and today does not work
error code:
> Error: [WALLET.SIGN_TX_ERROR] Cannot read properties of null (reading 'parameters')
>     at sa.signAndExecuteTransactionBlock (index.js:9994:13)
>     at async Object.signAndExecuteTransactionBlock (index.js:10298:12)

**Comment by bruceeewong** [comment]
@qxyanda Hi, Can you provide the version you are using?

**Comment by qxyanda** [comment]
> @qxyanda Hi, Can you provide the version you are using?

"@suiet/wallet-kit": "^0.2.19"

**Comment by qxyanda** [comment]
> @qxyanda Hi, Can you provide the version you are using?

it works now, i think its devnet error,thx anyway
