### ISSUE TITLE
Cannot verify signature in example

### ISSUE THREAD

**Issue by Sotatek-HungNguyenThanh** [suiet/wallet-kit#285]
signMessage succeed, but verify signedMessage failed

![Screenshot 2024-02-05 at 11 49 28 AM](https://github.com/suiet/wallet-kit/assets/25896304/55255ebc-cdab-4571-955e-b51b007c9f57)

**Comment by bruceeewong** [comment]
Hi, I just tried using the latest main branch to test the signing and verification, and they work. Can you confirm if the code of wallet kit is the latest?
