### ISSUE TITLE
signPersonalMessage can't result valid signature

### ISSUE THREAD

**Issue by chaoyi7** [suiet/wallet-kit#286]
### Problem

Can `@suiet/wallet-kit` support wallet switch?

simple code below
```
wallet.adapter?.signPersonalMessage({ account: account!, message: new TextEncoder().encode('HelloXXX') })
```
Let's say I've logged in to a wallet now, and there's a ListBox comp in the upper right corner of my page to switch wallet addresses, when I switch, I call the`signPersonalMessage` method, and then request the API after getting the signature, but I find that I can't get a valid signature using SignPersonalMessage

```
const verifyResult = await wallet.verifySignedMessage(res, account.publicKey)
console.log('verify signedMessage', verifyResult)  // is false
```

**Comment by bruceeewong** [comment]
Hi, currently our wallet kit does not support wallet switching from the DApp side. May I know how do you implement the switching logic? Can you also verify if the account of the "account.publicKey" is the one that the DApp connects to?

**Comment by bruceeewong** [comment]
Close due to no response for a long time.
