### ISSUE TITLE
Error when using swap

### ISSUE THREAD

**Issue by AntonBabundin** [suiet/wallet-kit#294]
<img width="363" alt="Снимок экрана 2024-05-07 в 00 22 36" src="https://github.com/suiet/wallet-kit/assets/59487235/74da74c8-5bc3-4fb0-9fee-0b2ba16c7022">

**Comment by bruceeewong** [comment]
Hey there, this is not relevant to the context of wallet kit. So I am going to close the issue.
By the way, this should be a bug that has been solved. If you still have issues, please submit issues to the repo of Suiet wallet: https://github.com/suiet/suiet
