### ISSUE TITLE
Is there an infinite loop in the program?

### ISSUE THREAD

**Issue by songen01** [suiet/wallet-kit#73]
when i used wallet-kit before
![image](https://user-images.githubusercontent.com/109256176/202955648-5ccd8417-82a7-4d6c-9333-44efb881dc20.png)

after：
![image](https://user-images.githubusercontent.com/109256176/202955736-2244c119-40d6-4631-96a2-393f4fbc9623.png)

All three are like this：
![image](https://user-images.githubusercontent.com/109256176/202955816-08874198-ff36-4205-8f9f-6cd05497f281.png)

**Is there an infinite loop in it?**

**Comment by songen01** [comment]
https://wallet-kit-demo.vercel.app/   this website

**Comment by bruceeewong** [comment]
Thank

**Comment by bruceeewong** [comment]
Thank you for reporting the issue! It has been fixed by version @suiet/wallet-kit@0.1.7
Relevant commit: https://github.com/suiet/wallet-kit/commit/aded813c0a27bcdb4666bcc16ac2c2c7120008b1
