### ISSUE TITLE
Can I use this repo to check wallet balance and transfer some funds?

### ISSUE THREAD

**Issue by zydjohnHotmail** [suiet/wallet-kit#76]
Hello:
I found there is web browser extension wallet: Suiet Wallet, and I want to know the following:
Does the wallet support tokens (like USDT) on HECO chain?
Can I use the repo (do you have NPM for Node.js?) to check wallet balance and transfer received funds to another address via different network: like receive USDT via HECO network, and send to another address via ERC20/BEP20 network?
Please advise,

**Comment by zydjohnHotmail** [comment]
Hello:
Do you have plan to support multi-chain later?
Thanks,

**Comment by bruceeewong** [comment]
@zydjohnHotmail No, we don't have a plan to support multi-chain yet.

**Comment by zydjohnHotmail** [comment]
Thanks!
