### ISSUE TITLE
Not working with Next.js 13

### ISSUE THREAD

**Issue by P233** [suiet/wallet-kit#77]
Next.js 13 no longer supports any polyfills, but this package contains the `whatwg-fetch` polyfill (probably came from `sui.js`), so there is an incompatible issue:

```
Collecting page data .TypeError: Cannot set property Headers of #<Object> which has only a getter
```

I am not sure what's the best solution. Maybe add a new build that doesn't include the fetch polyfill? For example, adding the following code to `vite.config.ts`

```
external: ["react", "react-dom", "cross-fetch", "cross-fetch/polyfill"],
```

**Comment by collin-aftermath** [comment]
Having the same problem.

**Comment by wbh1328551759** [comment]
I have same problem, too

**Comment by leanllg** [comment]
We'll support nextjs 13 soon.

**Comment by bruceeewong** [comment]
@P233 This issue is exactly caused by containing @mysten/sui.js codes. I've already submit an relevant issue to Sui's repo https://github.com/MystenLabs/sui/issues/6377

Your suggestion doesn't work because the dependencies are bundled in sui.js sdk. But thanks for your feedback, we will work on this case and find out possible solutions.

**Comment by leanllg** [comment]
We publish a new alpha version 0.1.11-alpha.0 that doesn't include the fetch polyfill. You can use the version to solve the problem. And we add a nextjs example in the `nextjs` branch(https://github.com/suiet/wallet-kit/tree/nextjs).

**Comment by P233** [comment]
@leanllg Works like a charm. Thank you very much. 

@bruceeewong BTW, I have added `"cross-fetch"` and `"cross-fetch/polyfill"` to the `rollupOptions. external` field of  [vite.config.ts](https://github.com/suiet/wallet-kit/blob/main/packages/kit/vite.config.ts) and compiled locally. It actually works.
