### ISSUE TITLE
throws error when Suiet wallet is not initialized

### ISSUE THREAD

**Issue by joradn222** [suiet/wallet-kit#79]
When wallet is installed, but is not initialized, is throws error.

```
Unhandled Runtime Error
Error: [WalletError] Wallet not initialized
```

**Comment by bruceeewong** [comment]
Yes, it would throw this error. Does it not make sense or interrupt something?

**Comment by minhtuan251295** [comment]
Hi, I just have a suggestion in here. Could we handle this error by adding it to the useWallet hook? So it's easier to handle the UI for this error.

**Comment by bruceeewong** [comment]
@minhtuan251295 I think you can use try-catch for `connect` method of useWallet hook to capture this error, and then handle it in UI. Is there any problem?

**Comment by minhtuan251295** [comment]
Ah, I see. Just using connect button components 👍 Got it, thank you so much
