### ISSUE TITLE
How do I want my wallet to enter @suiet/wallet-kit?

### ISSUE THREAD

**Issue by ShaYha271097** [suiet/wallet-kit#81]

**Comment by bruceeewong** [comment]
Are you building a wallet project and wanna be covered in our kit?

**Comment by ShaYha271097** [comment]
yes

**Comment by bruceeewong** [comment]
@ShaYha271097 Do you have any introduction link for your wallet? Ideally if you implement [sui wallet-standard](https://github.com/MystenLabs/sui/tree/main/sdk/wallet-adapter/wallet-standard), it should show up in the wallet selector of our kit.
