### ISSUE TITLE
Disconnect wallet error

### ISSUE THREAD

**Issue by Shulepov** [suiet/wallet-kit#84]
In one of my projects I'm receiving an error when try to disconnect suiet wallet:
`TypeError: Cannot read properties of undefined (reading 'address')`
![2022-12-28 16 31 58](https://user-images.githubusercontent.com/1138750/209820038-b7dae61c-c3c1-4867-a123-63a7762d3a9e.jpg)

**Comment by minhtuan251295** [comment]
I faced this issue and solved that by upgrading to React 18

**Comment by fredliang44** [comment]
@Shulepov @minhtuan251295 you can checkout wallet-kit `v0.1.14`, this issue should have been resolved
