### ISSUE TITLE
Need help: No wallets showed in the Connect Wallet panel, how can I load the supported wallets?

### ISSUE THREAD

**Issue by qiwihui** [suiet/wallet-kit#92]
<img width="331" alt="Screenshot 2023-01-16 at 10 07 08" src="https://user-images.githubusercontent.com/3297411/212583511-c3846961-ce91-4a0c-8c5d-4fb44c116888.png">

**Comment by bruceeewong** [comment]
By default, it should show all the preset wallet items. I suppose you are customizing the list, right? Check out this tutorial: https://kit.suiet.app/docs/tutorial/customize-wallet-list

**Comment by qiwihui** [comment]
cool, I have seen the wallets I need. Thanks again.
